### ISSUE TITLE
Installing as non-root failure

### ISSUE THREAD

**Issue by evantill** [sbaerlocher/ansible.wp-cli#5]
Installing `wp-cli` for a user without root privileges result in `wp` not executable.

This is due to the `get_url` configuration using `root`:  

```yaml
---
# tasks file for sbaerlocher.wp-cli

- name: Install WP-CLI
  get_url:
    url: "{{ wp_cli_phar_url }}"
    dest: "{{ wp_cli_bin_path }}"
    force: true
    owner: root
    group: root
    mode: 0755
  tags:
    - packages
```
